### ISSUE TITLE
steamui.so

### ISSUE THREAD

**Issue by MrDarcyA** [OpenSteamClient/OpenSteamClient#38] opened 2024-01-27 09:36 UTC
I launched the client in my terminal and it printed out this error
"dlmopen steamui.so failed: steamui.so: cannot open shared object file: No such file or directory"
then seg faulted.

**Comment by MrDarcyA** [comment] 2024-01-27 09:37
Arch Linux user BTW

**Comment by Rosentti** [comment] 2024-01-27 09:43
It likes to segfault a bit. Try a couple more times.

**Comment by MrDarcyA** [comment] 2024-01-27 23:19
after restoring the official steam client is there anything I do before using open one again?

**Comment by MrDarcyA** [comment] 2024-01-28 03:43
still refuses to launch.
I haven't launched it successfully not even once.

**Comment by Rosentti** [comment] 2024-01-28 09:32
Ah. You're probably using the latest release? It's currently broken, but there's a build artifact available to download that should work. I'll send the link.

**Comment by Rosentti** [comment] 2024-01-28 09:33
https://github.com/OpenSteamClient/OpenSteamClient/actions/runs/7640025864/artifacts/1191594439

**Comment by Rosentti** [comment] 2024-01-28 09:36
Also, seems like a duplicate of #37

**Closed by Rosentti** 2024-01-28 09:36 UTC
